[
	{
		id: 1,
		name: 'Rick Sanchez',
		status: 'Alive',
		species: 'Human',
		type: '',
		gender: 'Male',
		location: {
			name: 'Earth (Replacement Dimension)',
			url: 'https://rickandmortyapi.com/api/location/20',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
		episode: [
			'https://rickandmortyapi.com/api/episode/1',
			'https://rickandmortyapi.com/api/episode/2',
			'https://rickandmortyapi.com/api/episode/3',
			'https://rickandmortyapi.com/api/episode/4',
			'https://rickandmortyapi.com/api/episode/5',
			'https://rickandmortyapi.com/api/episode/6',
			'https://rickandmortyapi.com/api/episode/7',
			'https://rickandmortyapi.com/api/episode/8',
			'https://rickandmortyapi.com/api/episode/9',
			'https://rickandmortyapi.com/api/episode/10',
			'https://rickandmortyapi.com/api/episode/11',
			'https://rickandmortyapi.com/api/episode/12',
			'https://rickandmortyapi.com/api/episode/13',
			'https://rickandmortyapi.com/api/episode/14',
			'https://rickandmortyapi.com/api/episode/15',
			'https://rickandmortyapi.com/api/episode/16',
			'https://rickandmortyapi.com/api/episode/17',
			'https://rickandmortyapi.com/api/episode/18',
			'https://rickandmortyapi.com/api/episode/19',
			'https://rickandmortyapi.com/api/episode/20',
			'https://rickandmortyapi.com/api/episode/21',
			'https://rickandmortyapi.com/api/episode/22',
			'https://rickandmortyapi.com/api/episode/23',
			'https://rickandmortyapi.com/api/episode/24',
			'https://rickandmortyapi.com/api/episode/25',
			'https://rickandmortyapi.com/api/episode/26',
			'https://rickandmortyapi.com/api/episode/27',
			'https://rickandmortyapi.com/api/episode/28',
			'https://rickandmortyapi.com/api/episode/29',
			'https://rickandmortyapi.com/api/episode/30',
			'https://rickandmortyapi.com/api/episode/31',
			'https://rickandmortyapi.com/api/episode/32',
			'https://rickandmortyapi.com/api/episode/33',
			'https://rickandmortyapi.com/api/episode/34',
			'https://rickandmortyapi.com/api/episode/35',
			'https://rickandmortyapi.com/api/episode/36',
			'https://rickandmortyapi.com/api/episode/37',
			'https://rickandmortyapi.com/api/episode/38',
			'https://rickandmortyapi.com/api/episode/39',
			'https://rickandmortyapi.com/api/episode/40',
			'https://rickandmortyapi.com/api/episode/41',
		],
		url: 'https://rickandmortyapi.com/api/character/1',
	},
	{
		id: 2,
		name: 'Morty Smith',
		status: 'Alive',
		species: 'Human',
		type: '',
		gender: 'Male',
		location: {
			name: 'Earth (Replacement Dimension)',
			url: 'https://rickandmortyapi.com/api/location/20',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
		episode: [
			'https://rickandmortyapi.com/api/episode/1',
			'https://rickandmortyapi.com/api/episode/2',
			'https://rickandmortyapi.com/api/episode/3',
			'https://rickandmortyapi.com/api/episode/4',
			'https://rickandmortyapi.com/api/episode/5',
			'https://rickandmortyapi.com/api/episode/6',
			'https://rickandmortyapi.com/api/episode/7',
			'https://rickandmortyapi.com/api/episode/8',
			'https://rickandmortyapi.com/api/episode/9',
			'https://rickandmortyapi.com/api/episode/10',
			'https://rickandmortyapi.com/api/episode/11',
			'https://rickandmortyapi.com/api/episode/12',
			'https://rickandmortyapi.com/api/episode/13',
			'https://rickandmortyapi.com/api/episode/14',
			'https://rickandmortyapi.com/api/episode/15',
			'https://rickandmortyapi.com/api/episode/16',
			'https://rickandmortyapi.com/api/episode/17',
			'https://rickandmortyapi.com/api/episode/18',
			'https://rickandmortyapi.com/api/episode/19',
			'https://rickandmortyapi.com/api/episode/20',
			'https://rickandmortyapi.com/api/episode/21',
			'https://rickandmortyapi.com/api/episode/22',
			'https://rickandmortyapi.com/api/episode/23',
			'https://rickandmortyapi.com/api/episode/24',
			'https://rickandmortyapi.com/api/episode/25',
			'https://rickandmortyapi.com/api/episode/26',
			'https://rickandmortyapi.com/api/episode/27',
			'https://rickandmortyapi.com/api/episode/28',
			'https://rickandmortyapi.com/api/episode/29',
			'https://rickandmortyapi.com/api/episode/30',
			'https://rickandmortyapi.com/api/episode/31',
			'https://rickandmortyapi.com/api/episode/32',
			'https://rickandmortyapi.com/api/episode/33',
			'https://rickandmortyapi.com/api/episode/34',
			'https://rickandmortyapi.com/api/episode/35',
			'https://rickandmortyapi.com/api/episode/36',
			'https://rickandmortyapi.com/api/episode/37',
			'https://rickandmortyapi.com/api/episode/38',
			'https://rickandmortyapi.com/api/episode/39',
			'https://rickandmortyapi.com/api/episode/40',
			'https://rickandmortyapi.com/api/episode/41',
		],
		url: 'https://rickandmortyapi.com/api/character/2',
	},
	{
		id: 3,
		name: 'Summer Smith',
		status: 'Alive',
		species: 'Human',
		type: '',
		gender: 'Female',
		location: {
			name: 'Earth (Replacement Dimension)',
			url: 'https://rickandmortyapi.com/api/location/20',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
		episode: [
			'https://rickandmortyapi.com/api/episode/6',
			'https://rickandmortyapi.com/api/episode/7',
			'https://rickandmortyapi.com/api/episode/8',
			'https://rickandmortyapi.com/api/episode/9',
			'https://rickandmortyapi.com/api/episode/10',
			'https://rickandmortyapi.com/api/episode/11',
			'https://rickandmortyapi.com/api/episode/12',
			'https://rickandmortyapi.com/api/episode/14',
			'https://rickandmortyapi.com/api/episode/15',
			'https://rickandmortyapi.com/api/episode/16',
			'https://rickandmortyapi.com/api/episode/17',
			'https://rickandmortyapi.com/api/episode/18',
			'https://rickandmortyapi.com/api/episode/19',
			'https://rickandmortyapi.com/api/episode/20',
			'https://rickandmortyapi.com/api/episode/21',
			'https://rickandmortyapi.com/api/episode/22',
			'https://rickandmortyapi.com/api/episode/23',
			'https://rickandmortyapi.com/api/episode/24',
			'https://rickandmortyapi.com/api/episode/25',
			'https://rickandmortyapi.com/api/episode/26',
			'https://rickandmortyapi.com/api/episode/27',
			'https://rickandmortyapi.com/api/episode/29',
			'https://rickandmortyapi.com/api/episode/30',
			'https://rickandmortyapi.com/api/episode/31',
			'https://rickandmortyapi.com/api/episode/32',
			'https://rickandmortyapi.com/api/episode/33',
			'https://rickandmortyapi.com/api/episode/34',
			'https://rickandmortyapi.com/api/episode/35',
			'https://rickandmortyapi.com/api/episode/36',
			'https://rickandmortyapi.com/api/episode/38',
			'https://rickandmortyapi.com/api/episode/39',
			'https://rickandmortyapi.com/api/episode/40',
			'https://rickandmortyapi.com/api/episode/41',
		],
		url: 'https://rickandmortyapi.com/api/character/3',
	},
	{
		id: 4,
		name: 'Beth Smith',
		status: 'Alive',
		species: 'Human',
		type: '',
		gender: 'Female',
		location: {
			name: 'Earth (Replacement Dimension)',
			url: 'https://rickandmortyapi.com/api/location/20',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
		episode: [
			'https://rickandmortyapi.com/api/episode/1',
			'https://rickandmortyapi.com/api/episode/2',
			'https://rickandmortyapi.com/api/episode/3',
			'https://rickandmortyapi.com/api/episode/4',
			'https://rickandmortyapi.com/api/episode/5',
			'https://rickandmortyapi.com/api/episode/6',
			'https://rickandmortyapi.com/api/episode/7',
			'https://rickandmortyapi.com/api/episode/8',
			'https://rickandmortyapi.com/api/episode/9',
			'https://rickandmortyapi.com/api/episode/10',
			'https://rickandmortyapi.com/api/episode/11',
			'https://rickandmortyapi.com/api/episode/12',
			'https://rickandmortyapi.com/api/episode/13',
			'https://rickandmortyapi.com/api/episode/14',
			'https://rickandmortyapi.com/api/episode/15',
			'https://rickandmortyapi.com/api/episode/16',
			'https://rickandmortyapi.com/api/episode/17',
			'https://rickandmortyapi.com/api/episode/18',
			'https://rickandmortyapi.com/api/episode/19',
			'https://rickandmortyapi.com/api/episode/20',
			'https://rickandmortyapi.com/api/episode/21',
			'https://rickandmortyapi.com/api/episode/22',
			'https://rickandmortyapi.com/api/episode/23',
			'https://rickandmortyapi.com/api/episode/24',
			'https://rickandmortyapi.com/api/episode/25',
			'https://rickandmortyapi.com/api/episode/26',
			'https://rickandmortyapi.com/api/episode/27',
			'https://rickandmortyapi.com/api/episode/28',
			'https://rickandmortyapi.com/api/episode/29',
			'https://rickandmortyapi.com/api/episode/30',
			'https://rickandmortyapi.com/api/episode/31',
			'https://rickandmortyapi.com/api/episode/32',
			'https://rickandmortyapi.com/api/episode/33',
			'https://rickandmortyapi.com/api/episode/34',
			'https://rickandmortyapi.com/api/episode/35',
			'https://rickandmortyapi.com/api/episode/36',
			'https://rickandmortyapi.com/api/episode/37',
			'https://rickandmortyapi.com/api/episode/38',
			'https://rickandmortyapi.com/api/episode/39',
			'https://rickandmortyapi.com/api/episode/40',
			'https://rickandmortyapi.com/api/episode/41',
		],
		url: 'https://rickandmortyapi.com/api/character/4',
	},
	{
		id: 5,
		name: 'Jerry Smith',
		status: 'Alive',
		species: 'Human',
		type: '',
		gender: 'Male',
		location: {
			name: 'Earth (Replacement Dimension)',
			url: 'https://rickandmortyapi.com/api/location/20',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/5.jpeg',
		episode: [
			'https://rickandmortyapi.com/api/episode/6',
			'https://rickandmortyapi.com/api/episode/7',
			'https://rickandmortyapi.com/api/episode/8',
			'https://rickandmortyapi.com/api/episode/9',
			'https://rickandmortyapi.com/api/episode/10',
			'https://rickandmortyapi.com/api/episode/11',
			'https://rickandmortyapi.com/api/episode/12',
			'https://rickandmortyapi.com/api/episode/13',
			'https://rickandmortyapi.com/api/episode/14',
			'https://rickandmortyapi.com/api/episode/15',
			'https://rickandmortyapi.com/api/episode/16',
			'https://rickandmortyapi.com/api/episode/18',
			'https://rickandmortyapi.com/api/episode/19',
			'https://rickandmortyapi.com/api/episode/20',
			'https://rickandmortyapi.com/api/episode/21',
			'https://rickandmortyapi.com/api/episode/22',
			'https://rickandmortyapi.com/api/episode/23',
			'https://rickandmortyapi.com/api/episode/26',
			'https://rickandmortyapi.com/api/episode/29',
			'https://rickandmortyapi.com/api/episode/30',
			'https://rickandmortyapi.com/api/episode/31',
			'https://rickandmortyapi.com/api/episode/32',
			'https://rickandmortyapi.com/api/episode/33',
			'https://rickandmortyapi.com/api/episode/35',
			'https://rickandmortyapi.com/api/episode/36',
			'https://rickandmortyapi.com/api/episode/38',
			'https://rickandmortyapi.com/api/episode/39',
			'https://rickandmortyapi.com/api/episode/40',
			'https://rickandmortyapi.com/api/episode/41',
		],
		url: 'https://rickandmortyapi.com/api/character/5',
	},
	{
		id: 6,
		name: 'Abadango Cluster Princess',
		status: 'Alive',
		species: 'Alien',
		type: '',
		gender: 'Female',
		location: {
			name: 'Abadango',
			url: 'https://rickandmortyapi.com/api/location/2',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
		episode: [
			'https://rickandmortyapi.com/api/episode/1',
			'https://rickandmortyapi.com/api/episode/2',
			'https://rickandmortyapi.com/api/episode/3',
			'https://rickandmortyapi.com/api/episode/4',
			'https://rickandmortyapi.com/api/episode/5',
			'https://rickandmortyapi.com/api/episode/6',
			'https://rickandmortyapi.com/api/episode/7',
			'https://rickandmortyapi.com/api/episode/8',
			'https://rickandmortyapi.com/api/episode/9',
			'https://rickandmortyapi.com/api/episode/10',
			'https://rickandmortyapi.com/api/episode/11',
			'https://rickandmortyapi.com/api/episode/12',
			'https://rickandmortyapi.com/api/episode/13',
			'https://rickandmortyapi.com/api/episode/14',
			'https://rickandmortyapi.com/api/episode/15',
			'https://rickandmortyapi.com/api/episode/16',
			'https://rickandmortyapi.com/api/episode/17',
			'https://rickandmortyapi.com/api/episode/18',
			'https://rickandmortyapi.com/api/episode/19',
			'https://rickandmortyapi.com/api/episode/20',
			'https://rickandmortyapi.com/api/episode/21',
			'https://rickandmortyapi.com/api/episode/22',
			'https://rickandmortyapi.com/api/episode/23',
			'https://rickandmortyapi.com/api/episode/24',
			'https://rickandmortyapi.com/api/episode/25',
			'https://rickandmortyapi.com/api/episode/26',
			'https://rickandmortyapi.com/api/episode/27',
			'https://rickandmortyapi.com/api/episode/28',
			'https://rickandmortyapi.com/api/episode/29',
			'https://rickandmortyapi.com/api/episode/30',
			'https://rickandmortyapi.com/api/episode/31',
			'https://rickandmortyapi.com/api/episode/32',
			'https://rickandmortyapi.com/api/episode/33',
			'https://rickandmortyapi.com/api/episode/34',
			'https://rickandmortyapi.com/api/episode/35',
			'https://rickandmortyapi.com/api/episode/36',
			'https://rickandmortyapi.com/api/episode/37',
			'https://rickandmortyapi.com/api/episode/38',
			'https://rickandmortyapi.com/api/episode/39',
			'https://rickandmortyapi.com/api/episode/40',
			'https://rickandmortyapi.com/api/episode/41',
		],
		url: 'https://rickandmortyapi.com/api/character/6',
	},
	{
		id: 7,
		name: 'Abradolf Lincler',
		status: 'unknown',
		species: 'Human',
		type: 'Genetic experiment',
		gender: 'Male',
		location: {
			name: 'Abadango',
			url: 'https://rickandmortyapi.com/api/location/2',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
		episode: [
			'https://rickandmortyapi.com/api/episode/1',
			'https://rickandmortyapi.com/api/episode/2',
			'https://rickandmortyapi.com/api/episode/3',
			'https://rickandmortyapi.com/api/episode/4',
			'https://rickandmortyapi.com/api/episode/5',
			'https://rickandmortyapi.com/api/episode/6',
			'https://rickandmortyapi.com/api/episode/7',
			'https://rickandmortyapi.com/api/episode/8',
			'https://rickandmortyapi.com/api/episode/9',
			'https://rickandmortyapi.com/api/episode/10',
			'https://rickandmortyapi.com/api/episode/11',
			'https://rickandmortyapi.com/api/episode/12',
			'https://rickandmortyapi.com/api/episode/13',
			'https://rickandmortyapi.com/api/episode/14',
			'https://rickandmortyapi.com/api/episode/15',
			'https://rickandmortyapi.com/api/episode/16',
			'https://rickandmortyapi.com/api/episode/17',
			'https://rickandmortyapi.com/api/episode/18',
			'https://rickandmortyapi.com/api/episode/19',
			'https://rickandmortyapi.com/api/episode/20',
			'https://rickandmortyapi.com/api/episode/21',
			'https://rickandmortyapi.com/api/episode/22',
			'https://rickandmortyapi.com/api/episode/23',
			'https://rickandmortyapi.com/api/episode/24',
			'https://rickandmortyapi.com/api/episode/25',
			'https://rickandmortyapi.com/api/episode/26',
			'https://rickandmortyapi.com/api/episode/27',
			'https://rickandmortyapi.com/api/episode/28',
			'https://rickandmortyapi.com/api/episode/29',
			'https://rickandmortyapi.com/api/episode/30',
			'https://rickandmortyapi.com/api/episode/31',
			'https://rickandmortyapi.com/api/episode/32',
			'https://rickandmortyapi.com/api/episode/33',
			'https://rickandmortyapi.com/api/episode/34',
			'https://rickandmortyapi.com/api/episode/35',
			'https://rickandmortyapi.com/api/episode/36',
			'https://rickandmortyapi.com/api/episode/37',
			'https://rickandmortyapi.com/api/episode/38',
			'https://rickandmortyapi.com/api/episode/39',
			'https://rickandmortyapi.com/api/episode/40',
			'https://rickandmortyapi.com/api/episode/41',
		],
		url: 'https://rickandmortyapi.com/api/character/7',
	},
	{
		id: 8,
		name: 'Adjudicator Rick',
		status: 'Dead',
		species: 'Human',
		type: '',
		gender: 'Male',
		location: {
			name: 'Citadel of Ricks',
			url: 'https://rickandmortyapi.com/api/location/3',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/8.jpeg',
		episode: ['https://rickandmortyapi.com/api/episode/28'],
		url: 'https://rickandmortyapi.com/api/character/8',
	},
	{
		id: 9,
		name: 'Agency Director',
		status: 'Dead',
		species: 'Human',
		type: '',
		gender: 'Male',
		location: {
			name: 'Earth (Replacement Dimension)',
			url: 'https://rickandmortyapi.com/api/location/20',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/9.jpeg',
		episode: ['https://rickandmortyapi.com/api/episode/24'],
		url: 'https://rickandmortyapi.com/api/character/9',
	},
	{
		id: 10,
		name: 'Alan Rails',
		status: 'Dead',
		species: 'Human',
		type: 'Superhuman (Ghost trains summoner)',
		gender: 'Male',
		location: {
			name: "Worldender's lair",
			url: 'https://rickandmortyapi.com/api/location/4',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/10.jpeg',
		episode: ['https://rickandmortyapi.com/api/episode/25'],
		url: 'https://rickandmortyapi.com/api/character/10',
	},
	{
		id: 11,
		name: 'Albert Einstein',
		status: 'Dead',
		species: 'Human',
		type: '',
		gender: 'Male',
		location: {
			name: 'Earth (Replacement Dimension)',
			url: 'https://rickandmortyapi.com/api/location/20',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/11.jpeg',
		episode: ['https://rickandmortyapi.com/api/episode/12'],
		url: 'https://rickandmortyapi.com/api/character/11',
	},
	{
		id: 12,
		name: 'Alexander',
		status: 'Dead',
		species: 'Human',
		type: '',
		gender: 'Male',
		location: {
			name: 'Anatomy Park',
			url: 'https://rickandmortyapi.com/api/location/5',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/12.jpeg',
		episode: ['https://rickandmortyapi.com/api/episode/3'],
		url: 'https://rickandmortyapi.com/api/character/12',
	},
	{
		id: 13,
		name: 'Alien Googah',
		status: 'unknown',
		species: 'Alien',
		type: '',
		gender: 'unknown',
		location: {
			name: 'Anatomy Park',
			url: 'https://rickandmortyapi.com/api/location/5',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/13.jpeg',
		episode: [
			'https://rickandmortyapi.com/api/episode/1',
			'https://rickandmortyapi.com/api/episode/2',
			'https://rickandmortyapi.com/api/episode/3',
			'https://rickandmortyapi.com/api/episode/4',
			'https://rickandmortyapi.com/api/episode/5',
			'https://rickandmortyapi.com/api/episode/6',
			'https://rickandmortyapi.com/api/episode/7',
			'https://rickandmortyapi.com/api/episode/8',
			'https://rickandmortyapi.com/api/episode/9',
			'https://rickandmortyapi.com/api/episode/10',
			'https://rickandmortyapi.com/api/episode/11',
			'https://rickandmortyapi.com/api/episode/12',
			'https://rickandmortyapi.com/api/episode/13',
			'https://rickandmortyapi.com/api/episode/14',
			'https://rickandmortyapi.com/api/episode/15',
			'https://rickandmortyapi.com/api/episode/16',
			'https://rickandmortyapi.com/api/episode/17',
			'https://rickandmortyapi.com/api/episode/18',
			'https://rickandmortyapi.com/api/episode/19',
			'https://rickandmortyapi.com/api/episode/20',
			'https://rickandmortyapi.com/api/episode/21',
			'https://rickandmortyapi.com/api/episode/22',
			'https://rickandmortyapi.com/api/episode/23',
			'https://rickandmortyapi.com/api/episode/24',
			'https://rickandmortyapi.com/api/episode/25',
			'https://rickandmortyapi.com/api/episode/26',
			'https://rickandmortyapi.com/api/episode/27',
			'https://rickandmortyapi.com/api/episode/28',
			'https://rickandmortyapi.com/api/episode/29',
			'https://rickandmortyapi.com/api/episode/30',
			'https://rickandmortyapi.com/api/episode/31',
			'https://rickandmortyapi.com/api/episode/32',
			'https://rickandmortyapi.com/api/episode/33',
			'https://rickandmortyapi.com/api/episode/34',
			'https://rickandmortyapi.com/api/episode/35',
			'https://rickandmortyapi.com/api/episode/36',
			'https://rickandmortyapi.com/api/episode/37',
			'https://rickandmortyapi.com/api/episode/38',
			'https://rickandmortyapi.com/api/episode/39',
			'https://rickandmortyapi.com/api/episode/40',
			'https://rickandmortyapi.com/api/episode/41',
		],
		url: 'https://rickandmortyapi.com/api/character/13',
	},
	{
		id: 14,
		name: 'Alien Morty',
		status: 'unknown',
		species: 'Alien',
		type: '',
		gender: 'Male',
		location: {
			name: 'Anatomy Park',
			url: 'https://rickandmortyapi.com/api/location/5',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/14.jpeg',
		episode: ['https://rickandmortyapi.com/api/episode/10'],
		url: 'https://rickandmortyapi.com/api/character/14',
	},
	{
		id: 15,
		name: 'Alien Rick',
		status: 'unknown',
		species: 'Alien',
		type: '',
		gender: 'Male',
		location: {
			name: 'Anatomy Park',
			url: 'https://rickandmortyapi.com/api/location/5',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/15.jpeg',
		episode: [
			'https://rickandmortyapi.com/api/episode/1',
			'https://rickandmortyapi.com/api/episode/2',
			'https://rickandmortyapi.com/api/episode/3',
			'https://rickandmortyapi.com/api/episode/4',
			'https://rickandmortyapi.com/api/episode/5',
			'https://rickandmortyapi.com/api/episode/6',
			'https://rickandmortyapi.com/api/episode/7',
			'https://rickandmortyapi.com/api/episode/8',
			'https://rickandmortyapi.com/api/episode/9',
			'https://rickandmortyapi.com/api/episode/10',
			'https://rickandmortyapi.com/api/episode/11',
			'https://rickandmortyapi.com/api/episode/12',
			'https://rickandmortyapi.com/api/episode/13',
			'https://rickandmortyapi.com/api/episode/14',
			'https://rickandmortyapi.com/api/episode/15',
			'https://rickandmortyapi.com/api/episode/16',
			'https://rickandmortyapi.com/api/episode/17',
			'https://rickandmortyapi.com/api/episode/18',
			'https://rickandmortyapi.com/api/episode/19',
			'https://rickandmortyapi.com/api/episode/20',
			'https://rickandmortyapi.com/api/episode/21',
			'https://rickandmortyapi.com/api/episode/22',
			'https://rickandmortyapi.com/api/episode/23',
			'https://rickandmortyapi.com/api/episode/24',
			'https://rickandmortyapi.com/api/episode/25',
			'https://rickandmortyapi.com/api/episode/26',
			'https://rickandmortyapi.com/api/episode/27',
			'https://rickandmortyapi.com/api/episode/28',
			'https://rickandmortyapi.com/api/episode/29',
			'https://rickandmortyapi.com/api/episode/30',
			'https://rickandmortyapi.com/api/episode/31',
			'https://rickandmortyapi.com/api/episode/32',
			'https://rickandmortyapi.com/api/episode/33',
			'https://rickandmortyapi.com/api/episode/34',
			'https://rickandmortyapi.com/api/episode/35',
			'https://rickandmortyapi.com/api/episode/36',
			'https://rickandmortyapi.com/api/episode/37',
			'https://rickandmortyapi.com/api/episode/38',
			'https://rickandmortyapi.com/api/episode/39',
			'https://rickandmortyapi.com/api/episode/40',
			'https://rickandmortyapi.com/api/episode/41',
		],
		url: 'https://rickandmortyapi.com/api/character/15',
	},
	{
		id: 16,
		name: 'Amish Cyborg',
		status: 'Dead',
		species: 'Alien',
		type: 'Parasite',
		gender: 'Male',
		origin: {},
		location: {},
		image: 'https://rickandmortyapi.com/api/character/avatar/16.jpeg',
		episode: [
			'https://rickandmortyapi.com/api/episode/1',
			'https://rickandmortyapi.com/api/episode/2',
			'https://rickandmortyapi.com/api/episode/3',
			'https://rickandmortyapi.com/api/episode/4',
			'https://rickandmortyapi.com/api/episode/5',
			'https://rickandmortyapi.com/api/episode/6',
			'https://rickandmortyapi.com/api/episode/7',
			'https://rickandmortyapi.com/api/episode/8',
			'https://rickandmortyapi.com/api/episode/9',
			'https://rickandmortyapi.com/api/episode/10',
			'https://rickandmortyapi.com/api/episode/11',
			'https://rickandmortyapi.com/api/episode/12',
			'https://rickandmortyapi.com/api/episode/13',
			'https://rickandmortyapi.com/api/episode/14',
			'https://rickandmortyapi.com/api/episode/15',
			'https://rickandmortyapi.com/api/episode/16',
			'https://rickandmortyapi.com/api/episode/17',
			'https://rickandmortyapi.com/api/episode/18',
			'https://rickandmortyapi.com/api/episode/19',
			'https://rickandmortyapi.com/api/episode/20',
			'https://rickandmortyapi.com/api/episode/21',
			'https://rickandmortyapi.com/api/episode/22',
			'https://rickandmortyapi.com/api/episode/23',
			'https://rickandmortyapi.com/api/episode/24',
			'https://rickandmortyapi.com/api/episode/25',
			'https://rickandmortyapi.com/api/episode/26',
			'https://rickandmortyapi.com/api/episode/27',
			'https://rickandmortyapi.com/api/episode/28',
			'https://rickandmortyapi.com/api/episode/29',
			'https://rickandmortyapi.com/api/episode/30',
			'https://rickandmortyapi.com/api/episode/31',
			'https://rickandmortyapi.com/api/episode/32',
			'https://rickandmortyapi.com/api/episode/33',
			'https://rickandmortyapi.com/api/episode/34',
			'https://rickandmortyapi.com/api/episode/35',
			'https://rickandmortyapi.com/api/episode/36',
			'https://rickandmortyapi.com/api/episode/37',
			'https://rickandmortyapi.com/api/episode/38',
			'https://rickandmortyapi.com/api/episode/39',
			'https://rickandmortyapi.com/api/episode/40',
			'https://rickandmortyapi.com/api/episode/41',
		],
		url: 'https://rickandmortyapi.com/api/character/16',
	},
	{
		id: 17,
		name: 'Annie',
		status: 'Alive',
		species: 'Human',
		type: '',
		gender: 'Female',
		origin: {},
		location: {},
		image: 'https://rickandmortyapi.com/api/character/avatar/17.jpeg',
		episode: [
			'https://rickandmortyapi.com/api/episode/1',
			'https://rickandmortyapi.com/api/episode/2',
			'https://rickandmortyapi.com/api/episode/3',
			'https://rickandmortyapi.com/api/episode/4',
			'https://rickandmortyapi.com/api/episode/5',
			'https://rickandmortyapi.com/api/episode/6',
			'https://rickandmortyapi.com/api/episode/7',
			'https://rickandmortyapi.com/api/episode/8',
			'https://rickandmortyapi.com/api/episode/9',
			'https://rickandmortyapi.com/api/episode/10',
			'https://rickandmortyapi.com/api/episode/11',
			'https://rickandmortyapi.com/api/episode/12',
			'https://rickandmortyapi.com/api/episode/13',
			'https://rickandmortyapi.com/api/episode/14',
			'https://rickandmortyapi.com/api/episode/15',
			'https://rickandmortyapi.com/api/episode/16',
			'https://rickandmortyapi.com/api/episode/17',
			'https://rickandmortyapi.com/api/episode/18',
			'https://rickandmortyapi.com/api/episode/19',
			'https://rickandmortyapi.com/api/episode/20',
			'https://rickandmortyapi.com/api/episode/21',
			'https://rickandmortyapi.com/api/episode/22',
			'https://rickandmortyapi.com/api/episode/23',
			'https://rickandmortyapi.com/api/episode/24',
			'https://rickandmortyapi.com/api/episode/25',
			'https://rickandmortyapi.com/api/episode/26',
			'https://rickandmortyapi.com/api/episode/27',
			'https://rickandmortyapi.com/api/episode/28',
			'https://rickandmortyapi.com/api/episode/29',
			'https://rickandmortyapi.com/api/episode/30',
			'https://rickandmortyapi.com/api/episode/31',
			'https://rickandmortyapi.com/api/episode/32',
			'https://rickandmortyapi.com/api/episode/33',
			'https://rickandmortyapi.com/api/episode/34',
			'https://rickandmortyapi.com/api/episode/35',
			'https://rickandmortyapi.com/api/episode/36',
			'https://rickandmortyapi.com/api/episode/37',
			'https://rickandmortyapi.com/api/episode/38',
			'https://rickandmortyapi.com/api/episode/39',
			'https://rickandmortyapi.com/api/episode/40',
			'https://rickandmortyapi.com/api/episode/41',
		],
		url: 'https://rickandmortyapi.com/api/character/17',
	},
	{
		id: 18,
		name: 'Antenna Morty',
		status: 'Alive',
		species: 'Human',
		type: 'Human with antennae',
		gender: 'Male',
		location: {
			name: 'Citadel of Ricks',
			url: 'https://rickandmortyapi.com/api/location/3',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/18.jpeg',
		episode: [
			'https://rickandmortyapi.com/api/episode/10',
			'https://rickandmortyapi.com/api/episode/28',
		],
		url: 'https://rickandmortyapi.com/api/character/18',
	},
	{
		id: 19,
		name: 'Antenna Rick',
		status: 'unknown',
		species: 'Human',
		type: 'Human with antennae',
		gender: 'Male',
		location: {
			name: 'Interdimensional Cable',
			url: 'https://rickandmortyapi.com/api/location/6',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/19.jpeg',
		episode: ['https://rickandmortyapi.com/api/episode/10'],
		url: 'https://rickandmortyapi.com/api/character/19',
		created: '2017-11-04T22:28:13.756Z',
	},
	{
		id: 20,
		name: 'Ants in my Eyes Johnson',
		status: 'unknown',
		species: 'Human',
		type: 'Human with ants in his eyes',
		gender: 'Male',
		location: {
			name: 'Interdimensional Cable',
			url: 'https://rickandmortyapi.com/api/location/6',
		},
		image: 'https://rickandmortyapi.com/api/character/avatar/20.jpeg',
		episode: ['https://rickandmortyapi.com/api/episode/8'],
		url: 'https://rickandmortyapi.com/api/character/20',
	},
];
